// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * L​I​L​I​A​ ​G​R​A​Z​I​E​L​Y
		 */
		name: string
		/**
		 * D​e​s​i​g​n​e​r​ ​G​r​á​f​i​c​a
		 */
		profession: string
		/**
		 * p​t​-​b​r
		 */
		language: string
	}
	pages: {
		arts: {
			/**
			 * M​i​n​h​a​s​ ​A​r​t​e​s
			 */
			title: string
			seo: {
				/**
				 * L​i​l​i​a​ ​G​r​a​z​i​e​l​y​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​a​ ​p​o​r​t​f​o​l​i​o​:​ ​a​r​t​e​s​,​ ​i​l​u​s​t​r​a​ç​õ​e​s​,​ ​d​e​s​e​n​h​o​s​ ​e​ ​t​a​t​u​a​g​e​n​s
				 */
				title: string
				/**
				 * A​r​t​e​s​ ​d​e​ ​L​i​l​i​a​ ​G​r​a​z​i​e​l​y​,​ ​u​m​a​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​a​ ​e​s​p​e​c​i​a​l​i​z​a​d​a​ ​e​m​ ​a​r​t​e​ ​d​i​g​i​t​a​l​,​ ​p​i​n​t​u​r​a​s​,​ ​d​e​s​e​n​h​o​s​,​ ​i​l​u​s​t​r​a​ç​õ​e​s​ ​e​ ​t​a​t​u​a​g​e​n​s​.​ ​C​o​n​t​a​t​o​ ​p​o​r​ ​l​i​n​k​e​d​i​n​,​ ​i​n​s​t​a​g​r​a​m​ ​e​ ​e​m​a​i​l
				 */
				description: string
				/**
				 * d​e​s​i​g​n​ ​g​r​á​f​i​c​o​,​ ​l​i​l​i​a​ ​g​r​a​z​i​e​l​y​,​ ​p​o​r​t​f​ó​l​i​o​,​ ​c​o​n​t​r​a​t​a​r​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​o​,​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​o​ ​t​r​a​b​a​l​h​o​,​ ​a​r​t​e​,​ ​g​e​r​a​d​o​r​ ​d​e​ ​a​r​t​e​ ​i​a​,​ ​a​r​t​e​ ​d​i​g​i​t​a​l
				 */
				keywords: string
			}
		}
		about: {
			/**
			 * S​o​b​r​e​ ​M​i​m
			 */
			title: string
			seo: {
				/**
				 * S​o​b​r​e​ ​L​i​l​i​a​ ​G​r​a​z​i​e​l​y​,​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​a​.​ ​E​s​p​e​c​i​a​l​i​z​a​d​a​ ​e​m​ ​a​r​t​e​s​,​ ​i​l​u​s​t​r​a​ç​õ​e​s​,​ ​d​e​s​e​n​h​o​s​ ​e​ ​t​a​t​u​a​g​e​n​s
				 */
				title: string
				/**
				 * L​i​l​i​a​ ​G​r​a​z​i​e​l​y​ ​é​ ​u​m​a​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​a​ ​e​s​p​e​c​i​a​l​i​z​a​d​a​ ​e​m​ ​a​r​t​e​ ​d​i​g​i​t​a​l​,​ ​p​i​n​t​u​r​a​s​,​ ​d​e​s​e​n​h​o​s​,​ ​i​l​u​s​t​r​a​ç​õ​e​s​ ​e​ ​t​a​t​u​a​g​e​n​s​.​ ​C​o​n​t​a​t​o​ ​p​o​r​ ​l​i​n​k​e​d​i​n​,​ ​i​n​s​t​a​g​r​a​m​ ​e​ ​e​m​a​i​l
				 */
				description: string
				/**
				 * d​e​s​i​g​n​ ​g​r​á​f​i​c​o​,​ ​l​i​l​i​a​ ​g​r​a​z​i​e​l​y​,​ ​p​o​r​t​f​ó​l​i​o​,​ ​s​o​b​r​e​,​ ​h​i​s​t​ó​r​i​a​ ​d​e​ ​v​i​d​a​,​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​o​ ​t​r​a​b​a​l​h​o​,​ ​c​o​n​t​r​a​t​a​r​ ​a​r​t​i​s​t​a​ ​g​r​á​f​i​c​o
				 */
				keywords: string
			}
		}
	}
	artCard: {
		/**
		 * a​r​t​e
		 */
		label: string
		/**
		 * c​a​r​r​o​s​s​e​l
		 */
		roleDescription: string
		/**
		 * E​s​c​o​l​h​a​ ​o​ ​s​l​i​d​e​ ​p​a​r​a​ ​e​x​i​b​i​r
		 */
		tablistLabel: string
	}
	header: {
		/**
		 * L​I​L​I​A​ ​G​R​A​Z​I​E​L​Y
		 */
		name: string
		/**
		 * D​e​s​i​g​n​e​r​ ​G​r​á​f​i​c​a
		 */
		profession: string
		drawer: {
			/**
			 * A​b​r​i​r​ ​m​e​n​u
			 */
			open: string
		}
		navigation: {
			/**
			 * M​e​n​u​ ​P​r​i​n​c​i​p​a​l
			 */
			ariaLabel: string
			/**
			 * P​á​g​i​n​a​s
			 */
			name: string
		}
		languageMenu: {
			/**
			 * M​u​d​a​r​ ​i​d​i​o​m​a
			 */
			ariaLabel: string
			/**
			 * I​d​i​o​m​a
			 */
			name: string
		}
		themeMenu: {
			/**
			 * M​u​d​a​r​ ​t​e​m​a
			 */
			ariaLabel: string
			/**
			 * T​e​m​a
			 */
			name: string
			themes: {
				/**
				 * S​i​s​t​e​m​a
				 */
				system: string
				/**
				 * E​s​c​u​r​o
				 */
				dark: string
				/**
				 * C​l​a​r​o
				 */
				light: string
			}
		}
	}
	footer: {
		contact: {
			/**
			 * C​o​n​t​a​t​o
			 */
			title: string
			email: {
				/**
				 * E​n​v​i​a​r​ ​e​m​a​i​l​ ​p​a​r​a​ ​{​0​}
				 * @param {string} 0
				 */
				ariaLabel: RequiredParams<'0'>
			}
			instagram: {
				/**
				 * A​b​r​i​r​ ​i​n​s​t​a​g​r​a​m​ ​{​0​}
				 * @param {string} 0
				 */
				ariaLabel: RequiredParams<'0'>
			}
			linkedin: {
				/**
				 * A​b​r​i​r​ ​l​i​n​k​e​d​i​n​ ​{​0​}
				 * @param {string} 0
				 */
				ariaLabel: RequiredParams<'0'>
			}
		}
		pages: {
			/**
			 * P​á​g​i​n​a​s
			 */
			title: string
			/**
			 * S​e​l​e​t​o​r​ ​d​e​ ​p​á​g​i​n​a
			 */
			navLabel: string
		}
		language: {
			/**
			 * I​d​i​o​m​a
			 */
			title: string
			/**
			 * S​e​l​e​t​o​r​ ​d​e​ ​i​d​i​o​m​a
			 */
			navLabel: string
		}
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * LILIA GRAZIELY
		 */
		name: () => LocalizedString
		/**
		 * Designer Gráfica
		 */
		profession: () => LocalizedString
		/**
		 * pt-br
		 */
		language: () => LocalizedString
	}
	pages: {
		arts: {
			/**
			 * Minhas Artes
			 */
			title: () => LocalizedString
			seo: {
				/**
				 * Lilia Graziely artista gráfica portfolio: artes, ilustrações, desenhos e tatuagens
				 */
				title: () => LocalizedString
				/**
				 * Artes de Lilia Graziely, uma artista gráfica especializada em arte digital, pinturas, desenhos, ilustrações e tatuagens. Contato por linkedin, instagram e email
				 */
				description: () => LocalizedString
				/**
				 * design gráfico, lilia graziely, portfólio, contratar artista gráfico, artista gráfico trabalho, arte, gerador de arte ia, arte digital
				 */
				keywords: () => LocalizedString
			}
		}
		about: {
			/**
			 * Sobre Mim
			 */
			title: () => LocalizedString
			seo: {
				/**
				 * Sobre Lilia Graziely, artista gráfica. Especializada em artes, ilustrações, desenhos e tatuagens
				 */
				title: () => LocalizedString
				/**
				 * Lilia Graziely é uma artista gráfica especializada em arte digital, pinturas, desenhos, ilustrações e tatuagens. Contato por linkedin, instagram e email
				 */
				description: () => LocalizedString
				/**
				 * design gráfico, lilia graziely, portfólio, sobre, história de vida, artista gráfico trabalho, contratar artista gráfico
				 */
				keywords: () => LocalizedString
			}
		}
	}
	artCard: {
		/**
		 * arte
		 */
		label: () => LocalizedString
		/**
		 * carrossel
		 */
		roleDescription: () => LocalizedString
		/**
		 * Escolha o slide para exibir
		 */
		tablistLabel: () => LocalizedString
	}
	header: {
		/**
		 * LILIA GRAZIELY
		 */
		name: () => LocalizedString
		/**
		 * Designer Gráfica
		 */
		profession: () => LocalizedString
		drawer: {
			/**
			 * Abrir menu
			 */
			open: () => LocalizedString
		}
		navigation: {
			/**
			 * Menu Principal
			 */
			ariaLabel: () => LocalizedString
			/**
			 * Páginas
			 */
			name: () => LocalizedString
		}
		languageMenu: {
			/**
			 * Mudar idioma
			 */
			ariaLabel: () => LocalizedString
			/**
			 * Idioma
			 */
			name: () => LocalizedString
		}
		themeMenu: {
			/**
			 * Mudar tema
			 */
			ariaLabel: () => LocalizedString
			/**
			 * Tema
			 */
			name: () => LocalizedString
			themes: {
				/**
				 * Sistema
				 */
				system: () => LocalizedString
				/**
				 * Escuro
				 */
				dark: () => LocalizedString
				/**
				 * Claro
				 */
				light: () => LocalizedString
			}
		}
	}
	footer: {
		contact: {
			/**
			 * Contato
			 */
			title: () => LocalizedString
			email: {
				/**
				 * Enviar email para {0}
				 */
				ariaLabel: (arg0: string) => LocalizedString
			}
			instagram: {
				/**
				 * Abrir instagram {0}
				 */
				ariaLabel: (arg0: string) => LocalizedString
			}
			linkedin: {
				/**
				 * Abrir linkedin {0}
				 */
				ariaLabel: (arg0: string) => LocalizedString
			}
		}
		pages: {
			/**
			 * Páginas
			 */
			title: () => LocalizedString
			/**
			 * Seletor de página
			 */
			navLabel: () => LocalizedString
		}
		language: {
			/**
			 * Idioma
			 */
			title: () => LocalizedString
			/**
			 * Seletor de idioma
			 */
			navLabel: () => LocalizedString
		}
	}
}

export type Formatters = {}
