// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * O​i​,​ ​M​U​I​T​O​ ​B​O​M
	 */
	HI: string
}

export type TranslationFunctions = {
	/**
	 * Oi, MUITO BOM
	 */
	HI: () => LocalizedString
}

export type Formatters = {}
